config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'news' => 'static_pages#news'

  get 'gallery' => 'static_pages#gallery'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new,:create,:edit,:update]

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token, :reset_token
	before_save {self.email = email.downcase}
	validates :name, presence:true, length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length:{minimum:6}, allow_blank: true

    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
    	SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def forget
        update_attribute(:remember_digest,nil)
    end

    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end

    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end

    def password_reset_expired?
    reset_sent_at < 2.hours.ago
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success]= "Welcome onboard Pirate #{user.name.split.first}! Ship #{user.team} awaits.."
      redirect_back_or user 
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def news
  end

  def gallery
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit,:update, :destroy]
  before_action :correct_user, only: [:edit,:update] 
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page]) 
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success]= "Welcome onboard Pirate #{user.name.split.first}!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Kicked out!"
    redirect_to users_url
  end

  private

  		def user_params
  			params.require(:user).permit(:name,:email,:team,:password,:password_confirmation)
  		end

      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end

      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title_correction(page_title='')
		base_title = "Squadra Treasure Hunt '15"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] =user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
			
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user?(user)
		user == current_user
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar") 
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The Official Harbour for STH'15
	</small>
	<nav>
	Powered by <a href="http://www.ver-techs.com"> Vertechs </a>
		<ul>
			<li><%= link_to "Help", '#' %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<%= link_to "STH '15", root_path, id:"logo" %>
			<nav>
				<ul class="nav navbar-nav pull-right">
					<li><%= link_to "Home",root_path %></li>
					<li><%= link_to "Gallery",gallery_path %></li>
					<li><%= link_to "News",news_path %></li>
					<% if logged_in? %>
						<li><%= link_to "Users" , users_path%></li> 
						<li class ="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
						    <ul class="dropdown-menu">
              					<li><%= link_to "Profile", current_user %></li>
              					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
              					<li class="divider"></li>
          						<li>
                					<%= link_to "Log out", logout_path, method: "delete" %>
              					</li>
            				</ul>
          				</li>
					<% else %>
						<li> <%= link_to "Log in", login_path %>  </li>
					<% end %>	
				</ul>
			</nav>
		</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= title_correction(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%flash.each do |message_type,message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>	
		<%= render 'layouts/footer' %>	
		<%= debug(params) if Rails.env.development? %>
	</div>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
		Invalid entries. <%= pluralize(@user.errors.count,"error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %>

<h1>Contact us</h1>
<p>For more information on the upcoming Squadra Treasure Hunt contact mdse,nachu,jlee,awesome or sasi</p>

app/views/static_pages/gallery.html.erb
<% provide(:title,"Gallery") %>

<h1>Gallery</h1>
<p>Come back soon for memories of STH 14</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<p class="centeredImage">
		<%= link_to image_tag("logo.png", alt:"STH'15 logo", size:"150"), root_path %>
	</p>
	<h1>Squadra Treasure Hunt '15</h1>
	<h2>It's back! Bigger and better... stay tuned !!</h2>
	<% if !logged_in? %>
	<%= link_to "Register now!",signup_path,class: "btn btn-lg btn-primary" %> 
	<% else %>
	<%= link_to "Set Sail !",'#',class: "btn btn-lg btn-primary" %> 
	<% end %>
</div>

app/views/static_pages/news.html.erb
<% provide(:title,"News") %>


<h1>News</h1>
<p>
	<li> Organising committee formed for STH 15 - Bigger and Better
	<li> Work on STH15 website commenced on 8th Dec 2014

</p>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	 | <%= link_to "delete", user, method: :delete, data: {confirm: "Offboard this pirate?"} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,"Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name , class: 'form-control' %>
			<%= f.label :email %>
			<%= f.text_field :email , class: 'form-control' %>
			<%= f.label :team %>
			<%= f.select :team, [['STH Official','Official'],['Team A','a'],['Team B','b']], class: 'form-control' %>
			<%= f.label :password %>
      		<%= f.password_field :password , class: 'form-control'%>
      		<%= f.label :password_confirmation, "Confirmation" %>
      		<%= f.password_field :password_confirmation , class: 'form-control'%>

      		<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
  	</div>
</div>

app/views/users/index.html.erb
<% provide(:title,'All users') %>
<h1>Meet the pirates!</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name %>
			<%= f.text_field :name , class: 'form-control' %>
			<%= f.label :email %>
			<%= f.text_field :email , class: 'form-control' %>
			<%= f.label :team %>
			<%= f.select :team, [['STH Official','Official'],['Team A','a'],['Team B','b']], class: 'form-control' %>
			<%= f.label :password %>
      		<%= f.password_field :password , class: 'form-control'%>
      		<%= f.label :password_confirmation, "Confirmation" %>
      		<%= f.password_field :password_confirmation , class: 'form-control'%>

      		<%= f.submit "Register", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%#= gravator_for(@user) %>  
				<%= @user.name %>
			</h1>
			<h2>
				<%= @user.team %>
			</h2>
		</section>
	</aside>
</div>		

<div class="center jumbotron">
<%= link_to "Set Sail !",'#',class: "btn btn-lg btn-primary" %>
</div>